# Dependencies
markdown:         kramdown
highlighter:      true
plugins:             [jekyll-paginate]

# Permalinks
permalink:        none

# Setup
title:            code.Oliver
tagline:          'Notes, tinkerings, experiments'
url:              https://quantumleapliberia.com/
paginate:         3
paginate_path:    "blog/page:num"
excerpt_separator: "<!--more-->"
baseurl:          /
highlighter:      rouge
author:
  name:          Oliver Sumo
  url:            https://www.quantumleapliberia.com
  email:          quantumleaplib@gmail.com

# Custom vars
# github:
  # repo:           https://github.com/dsolivera/soliveras.com.git
blog_masthead_pages:
  Residential:          '/residential'
  Business:       '/business'
# personal_external_links:
  # linkedin:        'https://www.linkedin.com/in/solivera/'
  # twitter:         'https://twitter.com/solivera2g3'
  # github:          'https://github.com/dsolivera'
